<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9a90b56e-f55d-4f43-a879-a1b960cf1431</elementGuidId>
    <imagePath></imagePath>
    <name>img_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[src='https\:\/\/firebasestorage\.googleapis\.com\/v0\/b\/ecomerce-ai\.appspot\.com\/o\/products\%2F0jIJ3EsWSN5rT5elgEdF\?alt\=media\&amp;token\=e01705c9-9296-465c-9edc-d61bc4447171']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'product-card-img is-img-loaded')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>product-card-img is-img-loaded</value>
        <webElementGuid>de965ec6-4084-4b35-93da-1e849973a698</webElementGuid>
    </webElementProperties>
</WebElementEntity>