<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5e6a646e-fab3-41d3-a2f7-6074c39fd37a</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_bike_light</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#add-to-cart-sauce-labs-bike-light</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'add-to-cart-sauce-labs-bike-light') and equals(@name,'add-to-cart-sauce-labs-bike-light') and equals(@class,'btn btn_primary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_primary btn_small btn_inventory</value>
        <webElementGuid>8e04597b-17cc-4b8d-9911-8e7901f03b84</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bike-light</value>
        <webElementGuid>d4e2d167-2621-4cf2-ace3-247119b7fb31</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bike-light</value>
        <webElementGuid>3c08fbeb-2526-4407-9e1a-dbb55f41737a</webElementGuid>
    </webElementProperties>
</WebElementEntity>