<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fa547278-84a4-43ac-80d8-7719a4d45b5a</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_backpack</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#add-to-cart-sauce-labs-backpack</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'add-to-cart-sauce-labs-backpack') and equals(@name,'add-to-cart-sauce-labs-backpack') and equals(@class,'btn btn_primary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_primary btn_small btn_inventory</value>
        <webElementGuid>e9b22384-1e4b-4a64-aaa9-63388d244928</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-backpack</value>
        <webElementGuid>0e5e5b2b-31f2-489e-947b-7fbd7052b3bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-backpack</value>
        <webElementGuid>b8b85901-40f2-438d-b9b2-a007b59e2f47</webElementGuid>
    </webElementProperties>
</WebElementEntity>