<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4b5d3030-5f49-4ab5-9e69-161569453b52</elementGuidId>
    <imagePath></imagePath>
    <name>button_continue to shipping</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge css-110xwq5"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'CONTINUE TO SHIPPING')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>CONTINUE TO SHIPPING</value>
        <webElementGuid>e5845b0f-12d2-47c0-8ede-e31b3bff5732</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>e5845b0f-12d2-47c0-8ede-e31b3bff5732</webElementGuid>
    </webElementProperties>
</WebElementEntity>