<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8180ec4c-59f4-40ac-9049-fe9d9b3f16fd</elementGuidId>
    <imagePath></imagePath>
    <name>input_receive_marketing_info</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'receive_marketing_info') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>receive_marketing_info</value>
        <webElementGuid>89a2e746-e408-48c4-9488-191bd540fb72</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>89a2e746-e408-48c4-9488-191bd540fb72</webElementGuid>
    </webElementProperties>
</WebElementEntity>