<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bbb2b0d0-d361-48bd-9987-fc3d55e2db33</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/section[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.d-flex-center .button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'button button-small')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>button button-small</value>
        <webElementGuid>1658c97b-4427-482e-8f8a-c067af3912fd</webElementGuid>
    </webElementProperties>
</WebElementEntity>