<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5b9e648e-0d0b-4e7c-9fdc-7a15e59db902</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/section[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.d-flex-center .button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'button button-small')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>button button-small</value>
        <webElementGuid>09a1cd23-384f-4ac2-a59e-b92ff23b87d3</webElementGuid>
    </webElementProperties>
</WebElementEntity>