<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4522b49b-99b5-4dec-b72a-55477a4cdbd3</elementGuidId>
    <imagePath></imagePath>
    <name>input_shipping_address_city</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[5]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.bdl-shipping-form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':r6:') and equals(@name,'shipping_address.city') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>44ace107-b766-451c-9907-e2c74f09e525</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:r6:</value>
        <webElementGuid>c51afde4-bcad-4235-8181-243e159ff2f0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>shipping_address.city</value>
        <webElementGuid>cd8fe2c6-21c3-4295-bd69-ec0ec5ecb0ad</webElementGuid>
    </webElementProperties>
</WebElementEntity>