<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4b8ce7a6-11bb-46f5-a378-b00521c9800b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_iphone_15</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item\ in-stock\ products__item_3-in-row"]:nth-child(1) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'iPhone 15')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>iPhone 15</value>
        <webElementGuid>5fc73f2f-c167-4a9d-ba77-6ed7ab13bcae</webElementGuid>
    </webElementProperties>
</WebElementEntity>