<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5212949b-40cb-4b8d-bf08-75958b6ac34e</elementGuidId>
    <imagePath></imagePath>
    <name>main_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="page-layout__main"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>