<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5e2c1895-0eb4-4921-8983-bbadc1397984</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_go shopping</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/p[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn btn-success"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Go shopping!')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Go shopping!</value>
        <webElementGuid>e5845b0f-12d2-47c0-8ede-e31b3bff5732</webElementGuid>
    </webElementProperties>
</WebElementEntity>