<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>774a667d-1e7c-4de8-ad7e-e0f97089b340</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_samsung_galaxy_z_fold4_silicon_cover</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[5]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item\ in-stock\ products__item_3-in-row"]:nth-child(5) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Samsung Galaxy Z Fold4 Silicon Cover')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Samsung Galaxy Z Fold4 Silicon Cover</value>
        <webElementGuid>c220c0e2-89a7-4427-a81a-3eed40619408</webElementGuid>
    </webElementProperties>
</WebElementEntity>