<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7d8aca63-e52f-4280-9ddd-68f1ce6a5d13</elementGuidId>
    <imagePath></imagePath>
    <name>h2_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/h2[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="display"]:nth-child(2) [class="css-vbgp86-SkeletonTheme"]:nth-child(1) h2</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>