<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>394201da-97d7-4bf9-a051-ab85afedc407</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_shop</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="navigation-menu-main"] &gt; li:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Shop')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Shop</value>
        <webElementGuid>23f9cfcf-7d9b-439f-ad33-0fa2649c966e</webElementGuid>
    </webElementProperties>
</WebElementEntity>