<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fe313546-1e2c-42bc-ae55-b673b992c60d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_phone</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="horizontal-menu__root-element\ has-children"]:nth-child(1) [class="horizontal-menu__element\ is-link\ is-root"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Phone')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Phone</value>
        <webElementGuid>c220c0e2-89a7-4427-a81a-3eed40619408</webElementGuid>
    </webElementProperties>
</WebElementEntity>