<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5f8c5e5a-c0c8-4169-9faa-6dc88d4e5e08</elementGuidId>
    <imagePath></imagePath>
    <name>li_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>:root &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(3) &gt; :nth-child(3) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'horizontal-menu__root-element has-children')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>horizontal-menu__root-element has-children</value>
        <webElementGuid>04d046c9-f964-4861-a442-c9e9a4aacd79</webElementGuid>
    </webElementProperties>
</WebElementEntity>