<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f7e5d61a-48a8-49a2-b3a2-da1adde2d987</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[3]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.product-modal-action .button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'button button-small ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>button button-small </value>
        <webElementGuid>6a21f61f-80fe-40b6-b0af-a944e3359130</webElementGuid>
    </webElementProperties>
</WebElementEntity>