<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>83aa89bb-8918-459a-ba22-9ab66bf0a52c</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[3]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.product-modal-action .button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'button button-small ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>button button-small </value>
        <webElementGuid>3bc4e8a4-67d3-4f54-897f-d4f515f948d0</webElementGuid>
    </webElementProperties>
</WebElementEntity>