<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e2074409-38ac-422f-9866-9dc30259efb7</elementGuidId>
    <imagePath></imagePath>
    <name>div_react_select_2_option_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#react-select-2-option-1</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'react-select-2-option-1') and equals(@class,' css-yt9ioa-option')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value> css-yt9ioa-option</value>
        <webElementGuid>97a6b2bf-6c1a-49a4-a93c-f7157477a01b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>react-select-2-option-1</value>
        <webElementGuid>9ef105c6-d7b6-4edf-a069-9811eff0f738</webElementGuid>
    </webElementProperties>
</WebElementEntity>