<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>951ada75-a8cb-4f84-9fb3-3f079ea31a08</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.css-1hwfws3</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,' css-1hwfws3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value> css-1hwfws3</value>
        <webElementGuid>1d86667f-d908-4017-ac5d-97a685ee08cf</webElementGuid>
    </webElementProperties>
</WebElementEntity>