<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>19269a7f-6286-492a-9d91-37ebd76ab79b</elementGuidId>
    <imagePath></imagePath>
    <name>button_show_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[4]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[type="submit"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'Show (4)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Show (4)</value>
        <webElementGuid>5fc73f2f-c167-4a9d-ba77-6ed7ab13bcae</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>5fc73f2f-c167-4a9d-ba77-6ed7ab13bcae</webElementGuid>
    </webElementProperties>
</WebElementEntity>