<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>65116c72-f4eb-4631-9609-a40605518006</elementGuidId>
    <imagePath></imagePath>
    <name>button_checkout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#checkout</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'checkout') and equals(@name,'checkout') and equals(@class,'btn btn_action btn_medium checkout_button ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_action btn_medium checkout_button </value>
        <webElementGuid>f6f09cea-bb47-4c3a-93d1-b48d08c975fa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>checkout</value>
        <webElementGuid>8c51baee-63fc-4e35-8b14-125747447400</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>checkout</value>
        <webElementGuid>31c34bd7-f763-4eff-a248-338ba89ebdb2</webElementGuid>
    </webElementProperties>
</WebElementEntity>