<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2a7698f9-f23e-4e20-8490-0d7bb9db3a1a</elementGuidId>
    <imagePath></imagePath>
    <name>button_sign_in</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[1]/div[2]/form[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="button\ auth-button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'Sign In')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sign In</value>
        <webElementGuid>ba403adc-c81b-4337-87b7-e0d336e84e59</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>ba403adc-c81b-4337-87b7-e0d336e84e59</webElementGuid>
    </webElementProperties>
</WebElementEntity>