<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6ac14b2f-af25-4673-9bce-a0d37b902c5a</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-id='\32 05'] .btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-to-cart products__to-cart-btn') and equals(@title,'Add to cart')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-to-cart products__to-cart-btn</value>
        <webElementGuid>0281fadc-45b3-4600-b8e4-e5b98e31d505</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Add to cart</value>
        <webElementGuid>1b928348-e5dc-4e64-b21b-2805d1e63b10</webElementGuid>
    </webElementProperties>
</WebElementEntity>