<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>03599c8a-c628-4fd5-a6fc-aabf87a169f7</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.sort-buttons__element.active .sort-buttons__link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'sort-buttons__link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>sort-buttons__link</value>
        <webElementGuid>58ea232c-5a95-49c2-8685-2edca2ac94d7</webElementGuid>
    </webElementProperties>
</WebElementEntity>