<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>84d2d93b-c6d9-4ece-b9d0-f2e7dfecd32e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_product_google_pixel_pro</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[itemprop][href='\/product\/google-pixel-7-pro\?price_max\=2999\&amp;price_min\=674\&amp;in_stock\=1\&amp;category\=120']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>