<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>65b1d227-472d-4a4f-aa64-a8c956e5dd95</elementGuidId>
    <imagePath></imagePath>
    <name>input_price_min</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#desk_filter_price_min</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'desk_filter_price_min') and equals(@name,'price_min') and equals(@class,'form-control form-control-sm')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>form-control form-control-sm</value>
        <webElementGuid>8cdc630f-8061-4bf4-b951-d33cd41e3f4d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>desk_filter_price_min</value>
        <webElementGuid>9f4ad519-890c-4e6d-ab4f-69e67ded6ee8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>price_min</value>
        <webElementGuid>cb7b6a1d-d70a-4ff4-a1b5-5be5a868d67f</webElementGuid>
    </webElementProperties>
</WebElementEntity>