<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6b2c460c-0551-4aea-ae2e-65ca358f6a34</elementGuidId>
    <imagePath></imagePath>
    <name>input_price_min</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#desk_filter_price_min</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'desk_filter_price_min') and equals(@name,'price_min') and equals(@class,'form-control form-control-sm')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>form-control form-control-sm</value>
        <webElementGuid>e87f0fc7-0631-4472-9e05-d5cc0df8fc8f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>desk_filter_price_min</value>
        <webElementGuid>cc9016f8-d135-42b1-9326-5379575d18b1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>price_min</value>
        <webElementGuid>c8549f8b-7d3d-48c0-9f41-f4a706820c0a</webElementGuid>
    </webElementProperties>
</WebElementEntity>