<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>332f4e53-6842-4834-afd5-b7ac3eda9144</elementGuidId>
    <imagePath></imagePath>
    <name>input_price_max</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#desk_filter_price_max</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'desk_filter_price_max') and equals(@name,'price_max') and equals(@class,'form-control form-control-sm')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>form-control form-control-sm</value>
        <webElementGuid>79cdccf4-2d40-4187-8ed3-57556de697f0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>desk_filter_price_max</value>
        <webElementGuid>6388947f-c189-4961-8890-66d2dee5dc2c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>price_max</value>
        <webElementGuid>4cefa6c0-52e1-453e-8f07-663844b0ed43</webElementGuid>
    </webElementProperties>
</WebElementEntity>