<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>75e7299c-6d21-43b6-ad1b-4a3dd7d9b796</elementGuidId>
    <imagePath></imagePath>
    <name>input_price_max</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#desk_filter_price_max</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'desk_filter_price_max') and equals(@name,'price_max') and equals(@class,'form-control form-control-sm')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>form-control form-control-sm</value>
        <webElementGuid>2acd90ad-56dc-4680-9530-fd74f29356e5</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>desk_filter_price_max</value>
        <webElementGuid>52ccbbcd-f083-48d5-aaa9-d749ac4e7979</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>price_max</value>
        <webElementGuid>5bbd21a0-ed74-4676-96f0-2e74eb31f8a5</webElementGuid>
    </webElementProperties>
</WebElementEntity>