<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7669b322-ef0a-43d1-aff4-455b5f5340f5</elementGuidId>
    <imagePath></imagePath>
    <name>input_postalcode</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#postal-code</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'postal-code') and equals(@name,'postalCode') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>d7f8c514-1b10-4c33-8e71-7bf3fb5c9486</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>postal-code</value>
        <webElementGuid>a2a0da80-69bb-4963-9be4-5e837daf52b2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>postalCode</value>
        <webElementGuid>1293ee2e-7bd4-470e-a631-68d1def84153</webElementGuid>
    </webElementProperties>
</WebElementEntity>