<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f2f2bfee-e2db-448e-86a1-cf505615080f</elementGuidId>
    <imagePath></imagePath>
    <name>input_postalcode</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#postal-code</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'postal-code') and equals(@name,'postalCode') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>9a661354-1b9e-4a2f-869e-bc8217c3cbfa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>postal-code</value>
        <webElementGuid>5375bebd-190c-4cb7-ad88-32bde3fae686</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>postalCode</value>
        <webElementGuid>4a2a5a88-b119-4205-865f-ed7ebbe51434</webElementGuid>
    </webElementProperties>
</WebElementEntity>