<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f1de6b0b-04cf-4f3f-ad3c-d54785d3ceeb</elementGuidId>
    <imagePath></imagePath>
    <name>input_continue</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#continue</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'continue') and equals(@name,'continue') and equals(@class,'submit-button btn btn_primary cart_button btn_action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>submit-button btn btn_primary cart_button btn_action</value>
        <webElementGuid>1f7ed448-6ea6-4e51-98b0-2b9fd59ab0e2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>continue</value>
        <webElementGuid>1e72346d-2cd1-4009-af54-1d3576ed3fdb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>continue</value>
        <webElementGuid>2523f872-6b2a-42f4-ab31-6854abb590ed</webElementGuid>
    </webElementProperties>
</WebElementEntity>