<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>44d144ac-31d5-4284-84da-9144e427cc16</elementGuidId>
    <imagePath></imagePath>
    <name>input_lastname</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#last-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'last-name') and equals(@name,'lastName') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>aa3093b7-e050-483b-8f00-efa106c650d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>last-name</value>
        <webElementGuid>8ebc60ea-6bb5-4bb2-b5ba-045c9b264295</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>lastName</value>
        <webElementGuid>3a525754-3078-448f-8fbe-097091f59be8</webElementGuid>
    </webElementProperties>
</WebElementEntity>