<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4f7b5716-dd0c-4c7b-b542-ed229d8657a0</elementGuidId>
    <imagePath></imagePath>
    <name>input_continue</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#continue</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'continue') and equals(@name,'continue') and equals(@class,'submit-button btn btn_primary cart_button btn_action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>submit-button btn btn_primary cart_button btn_action</value>
        <webElementGuid>499c774d-3d2d-4de8-94ac-68bfd4750dc4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>continue</value>
        <webElementGuid>9e8d37a8-4254-4f4a-be31-9c5f538c2c3d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>continue</value>
        <webElementGuid>05a565ad-741e-4bee-a47b-cdd3b6f6f9c1</webElementGuid>
    </webElementProperties>
</WebElementEntity>