<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a88dc5e2-671c-4a84-9885-7e43abfb295b</elementGuidId>
    <imagePath></imagePath>
    <name>button_finish</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[9]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#finish</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'finish') and equals(@name,'finish') and equals(@class,'btn btn_action btn_medium cart_button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_action btn_medium cart_button</value>
        <webElementGuid>95da0237-3fee-48e8-a106-a0a20f26d50e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>finish</value>
        <webElementGuid>30cbeea3-6f2c-4da6-a427-d0480f12ac69</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>finish</value>
        <webElementGuid>420156aa-aaff-421d-92eb-d646bd556713</webElementGuid>
    </webElementProperties>
</WebElementEntity>